services:
  postgres:
    image: postgres:17
    container_name: ecommerce-postgres
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
    ports:
      - "5432:5432"

  redis:
    image: redis:8
    container_name: ecommerce-redis
    ports:
      - "6379:6379"