#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

PAGES_DIR="${PAGES_DIR:-pages}"
QUALITY_REPORTS_DIR="${QUALITY_REPORTS_DIR:-quality-reports}"

fail() {
  echo "Pages assembly failed: $*" >&2
  exit 1
}

require_file() {
  [[ -f "$1" ]] || fail "missing required file: $1"
}

require_dir() {
  [[ -d "$1" ]] || fail "missing required directory: $1"
}

case "$PAGES_DIR" in
  "" | "." | "/" | "\\" | ".." | "../"* | *"/../"* | *"/.." | /* | [A-Za-z]:*)
    fail "unsafe PAGES_DIR value: $PAGES_DIR"
    ;;
esac

PAGES_PATH="$(realpath -m "$PAGES_DIR")"
case "$PAGES_PATH" in
  "$ROOT_DIR/pages" | "$ROOT_DIR/target/"*)
    ;;
  *)
    fail "PAGES_DIR must resolve to pages/ or a directory under target/: $PAGES_DIR"
    ;;
esac

write_openapi_ui() {
  cat > "$PAGES_DIR/openapi/index.html" <<'EOF'
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Modular Monolith E-commerce API</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Generated OpenAPI reference for the Modular Monolith E-commerce project.">
  <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css">
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
  <script>
    window.onload = () => {
      window.ui = SwaggerUIBundle({
        url: "./openapi.json",
        dom_id: "#swagger-ui",
        deepLinking: true,
        presets: [SwaggerUIBundle.presets.apis],
        layout: "BaseLayout"
      });
    };
  </script>
</body>
</html>
EOF
}

write_test_report_index() {
  cat > "$PAGES_DIR/test-report/index.html" <<'EOF'
<!doctype html>
<html lang="en" data-theme="dark">
<head>
  <meta charset="utf-8">
  <title>Test Reports | Modular Monolith E-commerce</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Surefire and Failsafe HTML reports generated by CI.">
  <script>
    (function () {
      try {
        document.documentElement.dataset.theme = localStorage.getItem("portfolio-dashboard-theme") || "dark";
      } catch {
        document.documentElement.dataset.theme = "dark";
      }
    })();
  </script>
  <link rel="stylesheet" href="../assets/site.css">
</head>
<body>
  <a class="skip-link" href="#main-content">Skip to content</a>
  <header class="topbar">
    <div class="wrap topbar-inner">
      <a class="brand" href="../">Modular Monolith E-commerce</a>
      <nav class="nav" aria-label="Report navigation">
        <a href="../docs/">Docs index</a>
        <a href="../coverage/">Coverage</a>
        <button class="theme-toggle" type="button" data-theme-toggle aria-label="Switch to light mode">Light mode</button>
      </nav>
    </div>
  </header>
  <main id="main-content" class="page-shell">
    <h1>HTML Test Reports</h1>
    <p>Generated from Maven Surefire and Failsafe XML outputs during CI.</p>
    <ul>
      <li><a href="./shared-kernel/surefire.html">shared-kernel Surefire report</a></li>
      <li><a href="./catalog/surefire.html">catalog Surefire report</a></li>
      <li><a href="./orders/surefire.html">orders Surefire report</a></li>
      <li><a href="./payment/surefire.html">payment Surefire report</a></li>
      <li><a href="./ecommerce-app/surefire.html">ecommerce-app Surefire report</a></li>
      <li><a href="./ecommerce-app/failsafe.html">ecommerce-app Failsafe report</a></li>
    </ul>
  </main>
  <script src="../assets/theme.js" defer></script>
</body>
</html>
EOF
}

copy_test_reports() {
  local expected module file source
  local -a expected_reports=(
    "shared-kernel:surefire.html"
    "catalog:surefire.html"
    "orders:surefire.html"
    "payment:surefire.html"
    "ecommerce-app:surefire.html"
    "ecommerce-app:failsafe.html"
  )

  for expected in "${expected_reports[@]}"; do
    module="${expected%%:*}"
    file="${expected#*:}"
    source="$QUALITY_REPORTS_DIR/$module/target/reports/$file"
    if [[ ! -f "$source" ]]; then
      source="$module/target/reports/$file"
    fi
    require_file "$source"
    mkdir -p "$PAGES_DIR/test-report/$module"
    cp "$source" "$PAGES_DIR/test-report/$module/$file"
  done
}

add_jekyll_front_matter() {
  local file title escaped_title tmp
  while IFS= read -r -d '' file; do
    title="$(sed -n 's/^# //p' "$file" | head -n 1)"
    [[ -n "$title" ]] || fail "missing level-one title in $file"
    escaped_title="${title//\\/\\\\}"
    escaped_title="${escaped_title//\"/\\\"}"
    tmp="$(mktemp)"
    {
      printf -- "---\nlayout: default\ntitle: \"%s\"\n---\n\n" "$escaped_title"
      cat "$file"
    } > "$tmp"
    mv "$tmp" "$file"
  done < <(find "$PAGES_DIR/docs" -name "*.md" -print0)
}

validate_pages_source() {
  require_file "$PAGES_DIR/index.html"
  require_file "$PAGES_DIR/assets/site.css"
  require_file "$PAGES_DIR/assets/theme.js"
  require_file "$PAGES_DIR/_layouts/default.html"
  require_file "$PAGES_DIR/_config.yml"
  require_file "$PAGES_DIR/openapi/index.html"
  require_file "$PAGES_DIR/openapi/openapi.json"
  require_file "$PAGES_DIR/docs/index.md"
  require_file "$PAGES_DIR/docs/review-guide.md"
  require_file "$PAGES_DIR/docs/user-guide.md"
  require_file "$PAGES_DIR/docs/api.md"
  require_file "$PAGES_DIR/docs/architecture.md"
  require_file "$PAGES_DIR/docs/business-flow.md"
  require_file "$PAGES_DIR/docs/trade-offs.md"
  require_file "$PAGES_DIR/docs/testing.md"
  require_file "$PAGES_DIR/docs/ci-and-pages.md"
  require_file "$PAGES_DIR/docs/adr/index.md"
  require_file "$PAGES_DIR/javadoc/index.html"
  require_file "$PAGES_DIR/coverage/index.html"
  require_file "$PAGES_DIR/test-report/index.html"
  require_file "$PAGES_DIR/test-report/shared-kernel/surefire.html"
  require_file "$PAGES_DIR/test-report/catalog/surefire.html"
  require_file "$PAGES_DIR/test-report/orders/surefire.html"
  require_file "$PAGES_DIR/test-report/payment/surefire.html"
  require_file "$PAGES_DIR/test-report/ecommerce-app/surefire.html"
  require_file "$PAGES_DIR/test-report/ecommerce-app/failsafe.html"

  if [[ -e "$PAGES_DIR/dashboard" ]]; then
    fail "dashboard alias should not be published"
  fi
}

require_file "dashboard/index.html"
require_file "dashboard/assets/site.css"
require_file "dashboard/assets/theme.js"
require_file "dashboard/_layouts/default.html"
require_file "dashboard/_config.yml"
require_dir "docs"
require_file "ecommerce-app/target/generated-docs/openapi.json"
require_dir "target/reports/apidocs"

COVERAGE_SOURCE="$QUALITY_REPORTS_DIR/coverage-report/target/site/jacoco-aggregate"
if [[ ! -d "$COVERAGE_SOURCE" ]]; then
  COVERAGE_SOURCE="coverage-report/target/site/jacoco-aggregate"
fi
require_dir "$COVERAGE_SOURCE"

rm -rf -- "$PAGES_DIR" _site
mkdir -p "$PAGES_DIR"/{docs,openapi,javadoc,coverage,test-report}

cp -R dashboard/. "$PAGES_DIR/"
cp -R docs/. "$PAGES_DIR/docs/"
add_jekyll_front_matter

cp ecommerce-app/target/generated-docs/openapi.json "$PAGES_DIR/openapi/openapi.json"
write_openapi_ui

cp -R target/reports/apidocs/. "$PAGES_DIR/javadoc/"
cp -R "$COVERAGE_SOURCE"/. "$PAGES_DIR/coverage/"

write_test_report_index
copy_test_reports
validate_pages_source

echo "Pages source assembled in $PAGES_DIR"
